baseURL = 'https://nenssi.github.io/sql_ua/'
theme = 'ananke'
DefaultContentLanguage = 'uk'
custom_css = ["css/my_style.css"]

[languages]
  [languages.uk]
    languageName = 'Українська'
    title = 'SQL-розробка аналітика'
    contentDir = 'content/uk'
    weight = 1
    [languages.uk.params]
      show_social_icons = true
		
  [languages.en]
    languageName = 'English'
    title = 'SQL-development analytics'
    contentDir = 'content/en'
    weight = 2
    [languages.en.params]
      show_social_icons = true
		
# Меню UA
[[languages.uk.menu.main]]
    name = "Про мене"
    url = "/about/"
    weight = 1

[[languages.uk.menu.main]]
    name = "Блог"
    url = "/posts/"
    weight = 2

[[languages.uk.menu.main]]
    name = "Контакти"
    url = "/contact/"
    weight = 3

	
# Меню EN
[[languages.en.menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1

[[languages.en.menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[[languages.en.menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
	
	
[params]
    background_color_class = "bg-custom-green"
    show_social_icons = true
    
    [[params.social]]
        name = "github"
        url = "https://github.com/nenssi"
    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/oksana-bespalova-3b7b9a376/"
    [[params.social]]
        name = "telegram"
        url = "https://t.me/Nenssi7"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true